import numpy as np
import netCDF4 as nc
import h5py
import pyarrow.parquet as pq
import pyarrow.csv as pcsv
import torch
import zarr
import scipy.io as sio

from torch.utils.data import (
    # Core Datasets
    IterableDataset,
    StackDataset,
    ConcatDataset,
    ChainDataset,
    Subset,
    random_split,
    # Samplers
    Sampler,
    BatchSampler,
    RandomSampler,
    SequentialSampler,
    SubsetRandomSampler,
    WeightedRandomSampler,
    # Utils
    get_worker_info,
)

#-----------------------------------------------------------------------------------------------------------------------
# Helper Functions
#-----------------------------------------------------------------------------------------------------------------------

def numpy_convert(elem):
    """Converts a single element (or nested elements) to NumPy. Replaces default_convert."""
    if isinstance(elem, torch.Tensor):
        return elem.detach().cpu().numpy()
    elif isinstance(elem, np.ndarray):
        return elem
    elif isinstance(elem, (tuple, list)):
        return type(elem)(numpy_convert(x) for x in elem)
    elif isinstance(elem, dict):
        return {k: numpy_convert(v) for k, v in elem.items()}
    else:
        return elem

def numpy_collate(batch):
    """Recursively converts to NumPy and stacks the batch. Replaces default_collate."""
    elem = batch[0]
    
    if isinstance(elem, torch.Tensor):
        # Catch any rogue PyTorch tensors generated by legacy datasets
        return np.stack([x.detach().cpu().numpy() for x in batch])
    elif isinstance(elem, np.ndarray):
        return np.stack(batch)
    elif isinstance(elem, (int, float)):
        return np.array(batch)
    elif isinstance(elem, (tuple, list)):
        transposed = zip(*batch)
        return type(elem)(numpy_collate(samples) for samples in transposed)
    elif isinstance(elem, dict):
        return {key: numpy_collate([d[key] for d in batch]) for key in elem}
    else:
        raise TypeError(f"numpy_collate cannot handle batch of type {type(elem)}")

#-----------------------------------------------------------------------------------------------------------------------
# DataLoader
#-----------------------------------------------------------------------------------------------------------------------

class DataLoader(torch.utils.data.DataLoader):
    def __init__(self, dataset, batch_size=1, shuffle=False, num_workers=0, **kwargs):
        
        # If batching is enabled, use the collator to stack and convert
        if batch_size is not None and 'collate_fn' not in kwargs:
            kwargs['collate_fn'] = numpy_collate
            
        # If batching is disabled (None), use the converter to just convert
        elif batch_size is None and 'collate_fn' not in kwargs:
            kwargs['collate_fn'] = numpy_convert 
            
        kwargs['pin_memory'] = False 
        
        super().__init__(
            dataset=dataset,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            **kwargs
        )

#-----------------------------------------------------------------------------------------------------------------------
# Datasets
#-----------------------------------------------------------------------------------------------------------------------

class Dataset(torch.utils.data.Dataset):
    def __new__(cls, source=None, *args, **kwargs):
        if cls is not Dataset:
            return super().__new__(cls)

        if source is None:
            raise ValueError("ft.Dataset requires a source when instantiated directly.")

        if isinstance(source, (str, Path)):
            src_str = str(source).lower()

            if src_str.endswith(".zarr"):
                return ZarrDataset(source, *args, **kwargs)
            elif src_str.endswith((".h5", ".hdf5")):
                return HDF5Dataset(source, *args, **kwargs)
            elif src_str.endswith(".parquet"):
                return ParquetDataset(source, *args, **kwargs)
            elif src_str.endswith(".csv"):
                return CSVDataset(source, *args, **kwargs)
            elif src_str.endswith((".nc", ".nc4", ".netcdf")):
                return NetCDFDataset(source, *args, **kwargs)
            elif src_str.endswith(".mat"):
                return MATDataset(source, *args, **kwargs)
            else:
                raise ValueError(f"Unsupported data format extension: {source}")

        elif hasattr(source, "columns") and hasattr(source, "iloc"):
            return DataFrameDataset(source, *args, **kwargs)

        raise TypeError(f"Unsupported data source type: {type(source)}")

    def __getitem__(self, idx):
        raise NotImplementedError

    def __len__(self):
        raise NotImplementedError

#-----------------------------------------------------------------------------------------------------------------------
# Dataset Helpers
#-----------------------------------------------------------------------------------------------------------------------

# Zarr -----------------------------------------------------------------------------------------------------------------

class ZarrGroupProxy:
    """
    Lightweight, picklable proxy that maps dot-notation attributes 
    (e.g., dataset.conditions.Mach) directly to Zarr array slices or NumPy arrays.
    """

    def __init__(self, zarr_path: str, group_path: str = ""):
        self._zarr_path = zarr_path
        self._group_path = group_path

    def _get_zarr_obj(self):
        root = zarr.open_group(self._zarr_path, mode="r")
        return root[self._group_path] if self._group_path else root

    def __getattr__(self, name: str):
        # Prevent infinite recursion for internal Python attributes
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        obj = self._get_zarr_obj()

        if name not in obj:
            raise AttributeError(
                f"Zarr group '{self._group_path or 'root'}' has no subgroup or array '{name}'. "
                f"Available keys: {list(obj.keys())}"
            )

        target = obj[name]
        next_path = f"{self._group_path}/{name}" if self._group_path else name

        # If it's a subgroup, return another proxy layer
        if isinstance(target, zarr.hierarchy.Group):
            return ZarrGroupProxy(self._zarr_path, next_path)

        # If it's an array, return the array data as a NumPy view/array
        return target[:]

    def __dir__(self):
        """Enable autocompletion in IPython/VS Code for dynamic fields."""
        obj = self._get_zarr_obj()
        return list(obj.keys())


class ZarrDataset(Dataset):
    """
    A universal, auto-configuring Dataset that dynamically exposes any 
    Zarr array structure via dot-notation (e.g., dataset.conditions.Mach).
    """

    def __init__(self, zarr_path: str, primary_array: str = "polar_data"):
        self._zarr_path = str(zarr_path)
        self._primary_array_key = primary_array
        self._proxy = ZarrGroupProxy(self._zarr_path)

        # Determine dataset length from the primary data array without loading everything into memory
        root = zarr.open_group(self._zarr_path, mode="r")
        if primary_array not in root:
            raise KeyError(f"Primary array key '{primary_array}' not found in Zarr root.")

        self._len = root[primary_array].shape[0]

    def __getattr__(self, name: str):
        """Intercepts unknown attributes and forwards them to the root ZarrGroupProxy."""
        # Avoid intercepting standard Dataset internals or dunder methods
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        try:
            return getattr(self._proxy, name)
        except AttributeError as e:
            raise AttributeError(
                f"'{type(self).__name__}' object or underlying Zarr store has no attribute '{name}'"
            ) from e

    def __len__(self):
        return self._len

    def __getitem__(self, idx: int):
        """
        Default indexing behavior. Override this in downstream subclasses if custom 
        filtering (like separating feature vectors X and targets y) is needed.
        """
        root = zarr.open_group(self._zarr_path, mode="r")
        return root[self._primary_array_key][idx]

# DataFrames (Pandas/Polars) -------------------------------------------------------------------------------------------

class DataFrameDataset(Dataset):
    def __init__(self, df):
        # Extract to pure NumPy arrays immediately.
        # This strips the heavy Pandas metadata and allows safer multiprocessing.
        self._columns = list(df.columns)
        self._data = df.to_numpy(dtype=np.float32)
        self._len = len(self._data)
        
    def __getattr__(self, name):
        if name in self._columns:
            idx = self._columns.index(name)
            return self._data[:, idx]
        raise AttributeError(f"No column named '{name}'")
        
    def __len__(self):
        return self._len
        
    def __getitem__(self, idx):
        return self._data[idx]

# HDF5 -----------------------------------------------------------------------------------------------------------------

class HDF5GroupProxy:
    """Multiprocessing-safe proxy for navigating nested HDF5 groups and datasets."""

    def __init__(self, file_path: str, group_path: str = ""):
        self._file_path = str(file_path)
        self._group_path = group_path

    def _get_obj(self, f):
        return f[self._group_path] if self._group_path else f

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        with h5py.File(self._file_path, "r") as f:
            group = self._get_obj(f)
            if name not in group:
                raise AttributeError(
                    f"HDF5 path '{self._group_path or '/'}' has no item '{name}'"
                )

            target = group[name]
            next_path = f"{self._group_path}/{name}" if self._group_path else name

            if isinstance(target, h5py.Group):
                return HDF5GroupProxy(self._file_path, next_path)
            elif isinstance(target, h5py.Dataset):
                # Return data as NumPy array
                return target[...]


class HDF5Dataset(Dataset):
    """Dynamic proxy for HDF5 files."""

    def __init__(self, file_path: str, primary_key: str = "data"):
        self._file_path = str(file_path)
        self._primary_key = primary_key

        with h5py.File(self._file_path, "r") as f:
            if primary_key not in f:
                # Fallback to the first available dataset if primary_key is not specified
                datasets = [k for k in f.keys() if isinstance(f[k], h5py.Dataset)]
                if datasets:
                    self._primary_key = datasets[0]
                else:
                    raise KeyError(f"No datasets found in HDF5 root: {list(f.keys())}")

            self._len = f[self._primary_key].shape[0]

        self._proxy = HDF5GroupProxy(self._file_path)

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")
        return getattr(self._proxy, name)

    def __len__(self):
        return self._len

    def __getitem__(self, idx: int):
        with h5py.File(self._file_path, "r") as f:
            return f[self._primary_key][idx]

# Parquet --------------------------------------------------------------------------------------------------------------

class ParquetDataset(Dataset):
    """Dynamic proxy for Apache Parquet tabular data."""

    def __init__(self, file_path: str, target_column: str = None):
        self._file_path = str(file_path)
        
        # Read metadata only (fast, zero memory overhead)
        pf = pq.ParquetFile(self._file_path)
        self._len = pf.metadata.num_rows
        self._columns = pf.schema.names
        self._target_column = target_column or self._columns[-1]

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        if name in self._columns:
            # Read only the requested column into a NumPy array
            table = pq.read_table(self._file_path, columns=[name])
            return table.column(name).to_numpy()

        raise AttributeError(f"Parquet dataset has no column '{name}'. Available: {self._columns}")

    def __len__(self):
        return self._len

    def __getitem__(self, idx: int):
        # Slice the row across all columns or target column
        table = pq.read_table(self._file_path)
        return table.row(idx)

# Tensor/Arrays --------------------------------------------------------------------------------------------------------

class ArrayDataset(Dataset):
    """
    A direct JAX replacement for PyTorch's TensorDataset.
    Wraps arbitrary NumPy arrays along their first dimension.
    """
    def __init__(self, *arrays):
        assert all(arrays[0].shape[0] == array.shape[0] for array in arrays), \
            "Size mismatch between arrays"
        self.arrays = arrays

    def __getitem__(self, index):
        return tuple(array[index] for array in self.arrays)

    def __len__(self):
        return self.arrays[0].shape[0]

# CSV ------------------------------------------------------------------------------------------------------------------

class CSVDataset(Dataset):
    """Dynamic proxy for CSV files via PyArrow."""

    def __init__(self, file_path: str):
        self._file_path = str(file_path)
        
        # Parse table into memory-efficient Arrow format once on init
        self._table = pcsv.read_csv(self._file_path)
        self._columns = self._table.column_names
        self._data = {col: self._table.column(col).to_numpy() for col in self._columns}
        self._len = self._table.num_rows

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        if name in self._data:
            return self._data[name]

        raise AttributeError(f"CSV dataset has no column '{name}'. Available: {self._columns}")

    def __len__(self):
        return self._len

    def __getitem__(self, idx: int):
        return tuple(self._data[col][idx] for col in self._columns)

# NetCDF ---------------------------------------------------------------------------------------------------------------

class NetCDFGroupProxy:
    """Multiprocessing-safe proxy for NetCDF4 groups and variables."""

    def __init__(self, file_path: str, group_path: str = ""):
        self._file_path = str(file_path)
        self._group_path = group_path

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        with nc.Dataset(self._file_path, "r") as ds:
            grp = ds[self._group_path] if self._group_path else ds

            if name in grp.groups:
                next_path = f"{self._group_path}/{name}" if self._group_path else name
                return NetCDFGroupProxy(self._file_path, next_path)
            elif name in grp.variables:
                return grp.variables[name][:]

            raise AttributeError(f"NetCDF path '{self._group_path or '/'}' has no item '{name}'")


class NetCDFDataset(Dataset):
    """Dynamic proxy for NetCDF4 datasets."""

    def __init__(self, file_path: str, primary_variable: str = None):
        self._file_path = str(file_path)

        with nc.Dataset(self._file_path, "r") as ds:
            vars_list = list(ds.variables.keys())
            self._primary_variable = primary_variable or vars_list[0]
            self._len = ds.variables[self._primary_variable].shape[0]

        self._proxy = NetCDFGroupProxy(self._file_path)

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")
        return getattr(self._proxy, name)

    def __len__(self):
        return self._len

    def __getitem__(self, idx: int):
        with nc.Dataset(self._file_path, "r") as ds:
            return ds.variables[self._primary_variable][idx]

# MATLAB ---------------------------------------------------------------------------------------------------------------


class MATDataset(Dataset):
    """Dynamic proxy for MATLAB .mat workspace files (supports v4-v7.2 and v7.3 HDF5)."""

    def __init__(self, file_path: str, primary_key: str = None):
        self._file_path = str(file_path)
        self._data = {}

        # Attempt legacy SciPy loadmat first (v4, v6, v7.0-v7.2)
        try:
            mat = sio.loadmat(self._file_path)
            # Filter out MATLAB internal headers
            self._data = {
                k: v for k, v in mat.items() if not k.startswith("__")
            }
        except NotImplementedError:
            # Fall back to h5py for MATLAB v7.3 files
            with h5py.File(self._file_path, "r") as f:
                for k in f.keys():
                    if not k.startswith("#"):
                        self._data[k] = f[k][...]

        if not self._data:
            raise ValueError(f"No valid variables found in MAT file '{file_path}'")

        keys = list(self._data.keys())
        self._primary_key = primary_key or keys[0]
        self._len = len(self._data[self._primary_key])

    def __getattr__(self, name: str):
        if name.startswith("_"):
            raise AttributeError(f"'{type(self).__name__}' has no attribute '{name}'")

        if name in self._data:
            return self._data[name]

        raise AttributeError(f"MAT dataset has no variable '{name}'. Available: {list(self._data.keys())}")

    def __len__(self):
        return self._len

    def __getitem__(self, idx: int):
        return self._data[self._primary_key][idx]

__all__ = [
    "Dataset", "IterableDataset", "ArrayDataset", "StackDataset", "ConcatDataset", 
    "ChainDataset", "Subset", "random_split", "DataLoader", "get_worker_info", 
    "numpy_collate", "numpy_convert", "Sampler", "BatchSampler", "RandomSampler", 
    "SequentialSampler", "SubsetRandomSampler", "WeightedRandomSampler"
]