[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flowtangent"
version = "0.1.0"
description = "A differentiable, GPU-accelerated aerospace systems design environment."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beartype",
    "equinox",
    "jax",
    "jaxtyping",
    "beartype",
    "matplotlib",
    "networkx",
    "numcodecs",
    "numpy",
    "optimistix",
    "pandas",
    "plotly",
    "scikit-learn",
    "scipy",
    "tqdm",
    "zarr",
    "dask",
    "pyarrow"
]

[project.optional-dependencies]
dev = [
    "chex",
    "openmdao",
    "pycycle",
    "pytest",
    "nvidia-ml-py",
    "om-pycycle",
    "ruff"
]

[tool.ruff]
line-length = 120 

# Python 3.12 as the minimum
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors (spacing, indentation)
    "W",   # pycodestyle warnings
    "F",   # pyflakes (bugs, unused imports, undefined variables)
    "I",   # isort (automatically sorts your imports alphabetically)
    "N",   # pep8-naming (checks variable and class names)
    "NPY", # Numpy checks (function deprecation, legacy aliases)
    "PD",  # Pandas checks
]

ignore = [
    "E741", 
    "N802",
    "N803", 
    "N806",
    "N999"
]

[tool.ruff.format]
quote-style = "double" # Use double quotes for strings
indent-style = "space" # Indent with 4 spaces
skip-magic-trailing-comma = false  # Don't auto collapse things on separate lines

line-ending = "auto"

docstring-code-format = true
docstring-code-line-length = 60

[tool.ruff.lint.isort]
# Import block order
section-order = [
    "future",
    "standard-library",   # Native Python (os, sys, etc.)
    "third-party",        # Non-FT packages (jax, equinox, numpy, etc.)
    "first-party",        # FT imports
    "local-folder"        # Relative imports (e.g., from . import utils)
]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"numpy".msg = "Use jax.numpy as jnp in all computational modules to prevent XLA tracer crashes"

[tool.ruff.lint.per-file-ignores]
# Ignore unused imports (F401) and import sorting (I) globally for init files
"__init__.py" = ["F401", "I","E402"]

[tool.pytest.ini_options]
testpaths = ["tests"]       # Only look for tests in the tests/ directory
python_files = "test_*.py"  # Only run files that start with test_
addopts = "-p no:doctest"   # Explicitly disable doctest auto-discovery